const message = "Ready Player One is a 2011 science fiction novel, and the debut novel of American \n author Ernest Cline. The story, set in a dystopian 2044, follows protagonist Wade Watts on his \n search for an Easter egg in a worldwide virtual reality game, the discovery of which will lead him to \n inherit the game creator's fortune. Cline sold the rights to publish the novel in June 2010, in a \n bidding war to the Crown Publishing Group (a division of Random House)]. The book was published on \n August 16, 2011. An audiobook was released the same day; it was narrated by Wil Wheaton, who was \n mentioned briefly in one of the chapters.Ch. 20 In 2012, the book received an Alex Award from the \n Young Adult Library Services Association division of the American Library Association and won the 2012 \n Prometheus Award.";
console.log(message.toUpperCase());
console.log(message.toLowerCase());
const message1 = "Ready Player One is a 2011 science fiction novel, and the debut novel of American \n author Ernest Cline. The story, set in a dystopian 2044, follows protagonist Wade Watts on his \n search for an Easter egg in a worldwide virtual reality game, the discovery of which will lead \n him to inherit the game creator's fortune.";
const message1up = message1.toUpperCase();
const message2 = "Cline sold the rights to publish the novel in June 2010, in a bidding war to the Crown \n Publishing Group (a division of Random House)]. The book was published on August 16, 2011. An \n audiobook was released the same day; it was narrated by Wil Wheaton, who was mentioned briefly in \n one of the chapters.Ch. 20 In 2012, the book received an Alex Award from the Young Adult Library \n Services Association division of the American Library Association and won the 2012 Prometheus Award.";
const message2lo = message2.toLowerCase();
const result = message1up.concat(message2lo);
console.log(result);
console.log("The message has", result.length, "characters long")