const side1 = 10;
const side2 = 20;
const side3 = 5;
const result = side1 + side2 + side3;
const template = `2-nd way: Perimetr = ${side1} + ${side2} + ${side3} = ${result}`;
console.log("The Formula is: Perimetr = a + b + c");
console.log("where: a, b and c - are the lenght of each side (in our case = 10, 20 and 5)");
console.log("1-st way: Perimetr = " + side1 + " + " + side2 + " + " + side3 + " = " + result);
console.log(template);
console.log("  ^    ");
console.log('  5  ^   ');
console.log('  ^     20  ');
console.log('  ^        ^  ');
console.log('  ^^ 10 ^^^^^^^ ');