const firstname = "Yuriy";
const lastname = "Varchuk";
const age = 39;
const address = "123 Main Str";
const datebirth = "mm/dd/yyyy";
console.log('firstname: ', firstname);
console.log('lastname: ', lastname);
console.log('age: ', age);
console.log('address: ', address);
console.log('datebirth: ', datebirth);