const width = 5;
const height = 5;
const result = width * height;
const template = `2-nd way: Area = ${width} x ${height} = ${result}`;
console.log("The Formula is: Area = Width x Height or Area = S x S (S squared)");
console.log("where: S - is a lenght of one side (in our case = 5)");
console.log("1-st way: Area = " + width + " x " + height + " = " + result);
console.log(template);
console.log(' ---5--- ');
console.log('|       |');
console.log('5       5');
console.log('|       |');
console.log(' ---5--- ');