var firstname = "Yuriy";
var lastname = "Varchuk";
var age = 39;
var address = "123 Main Str";
var datebirth = "mm/dd/yyyy";
console.log(firstname);
console.log(lastname);
console.log(age);
console.log(address);
console.log(datebirth);