const one = 1;
const two = 2;
const three = 3;
const four = 4;
const five = 5;
const six = 6;
const seven = 7;
const eight = 8;
const nine = 9;
const ten = 10;
const result1 = nine * one;
const result2 = nine * two;
const result3 = nine * three;
const result4 = nine * four;
const result5 = nine * five;
const result6 = nine * six;
const result7 = nine * seven;
const result8 = nine * eight;
const result9 = nine * nine;
const result10 = nine * ten;
let template1 = `${nine} times ${one} equals ${result1}`;
let template2 = `${nine} times ${two} equals ${result2}`;
let template3 = `${nine} times ${three} equals ${result3}`;
let template4 = `${nine} times ${four} equals ${result4}`;
let template5 = `${nine} times ${five} equals ${result5}`;
let template6 = `${nine} times ${six} equals ${result6}`;
let template7 = `${nine} times ${seven} equals ${result7}`;
let template8 = `${nine} times ${eight} equals ${result8}`;
let template9 = `${nine} times ${nine} equals ${result9}`;
let template10 = `${nine} times ${ten} equals ${result10}`;
console.log(template1);
console.log(template2);
console.log(template3);
console.log(template4);
console.log(template5);
console.log(template6);
console.log(template7);
console.log(template8);
console.log(template9);
console.log(template10);
console.log(nine + " times " + one + " equals " + result1);
console.log(nine + " times " + two + " equals " + result2);
console.log(nine + " times " + three + " equals " + result3);
console.log(nine + " times " + four + " equals " + result4);
console.log(nine + " times " + five + " equals " + result5);
console.log(nine + " times " + six + " equals " + result6);
console.log(nine + " times " + seven + " equals " + result7);
console.log(nine + " times " + eight + " equals " + result8);
console.log(nine + " times " + nine + " equals " + result9);
console.log(nine + " times " + ten + " equals " + result10);